[wiki] Add Initial steps of commissioning Thread device via OTBR snap
MonicaisHer/openthread-border-router-snap pull request #4
Opened 2023-06-27 11:35 UTC by MonicaisHer

The purpose of this PR is to facilitate easier review and feedback on the content wiki page. The content of this PR will eventually be moved to the wiki page of this repository but will not be merged into the main branch.

2023-06-27 17:25 UTC, farshidtz requested changes
A simple and useful guide. I've added some minor comments.

2023-06-27 17:25 UTC, farshidtz commented on Wiki.md
> +Alternatively, these steps could also be performed in the GUI at http://0.0.0.0/.
The loopback interface address should be localhost or 127.0.0.1. Adresse 0.0.0.0 may work on some systems but it isn't usually used for this purpose.

2023-06-27 17:25 UTC, farshidtz commented on Wiki.md
> +Make sure the Thread lighting device is running. Flashing and running the Thread lighting device is beyond the scope of this guide.
```suggestion
Make sure the Thread lighting app is running. Flashing and running the Thread lighting app on the device is beyond the scope of this guide. 
```

2023-06-30 10:56 UTC, MonicaisHer commented
Close this PR, as the content has been moved to [wiki](https://github.com/MonicaisHer/openthread-border-router-snap/wiki/Commission-and-control-a-Matter-Thread-device-via-the-OTBR-Snap) page.

2023-06-30 10:56 UTC, closed without merging